# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: About
    url: '/#about'
    weight: 10
  - name: Resume
    url: '/resume'
    weight: 11    
  - name: Projects
    url: '/projects'
    weight: 20
  - name: Publications
    url: '/#publications'
    weight: 30
  - name: Teaching
    url: '/#teaching'
    weight: 40
  # - name: Students
  #   url: '/students'
  #   weight: 50
  # - name: Service
  #   url: '/service'
  #   weight: 60
  - name: Contact
    url: '/#contact'
    weight: 70

